/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import ArayuzIslemleri.GirisEkranIslemleri;
import ArayuzIslemleri.RenkVeIkonlar;
import MailConfig.MailIslemleri;
import SQLIslemleri.SQLKullaniciIslemleri;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import kullanicilar.Kullanici;

/**
 *
 * @author ocak
 */
public class GirisEkranı extends javax.swing.JFrame {
    
    // Değişkenler - DB İsimleri
    
    private String dbKullanici = "kullanicilar";
    
    

     RenkVeIkonlar renkIkon = new  RenkVeIkonlar();
     Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
     
     
     MailIslemleri mailIslemleri = new MailIslemleri();
     
     GirisEkranIslemleri girisEkranIslemleri;
     
     
     SQLKullaniciIslemleri kullaniciIslemleri = new SQLKullaniciIslemleri(mailIslemleri,dbKullanici);
     
     
     //Değişkenler
     
     public Integer posX;
     public Integer posY;
     
     private boolean sifreKurtarmaIslemi = false;
     

     private boolean sayacDurdur = false;
     private boolean sifreSonuc = false;
    
    /**
     * Creates new form GirisEkranı
     */
    public GirisEkranı() {
        initComponents();
        initComponents2(false);
        
         this.setLocation(dim.width/2-this.getSize().width/2,dim.height/2-this.getSize().height/2);
        
    }

    public void initComponents2(boolean acilis){
        
        jTextField_KurtarmaKodu.setVisible(acilis);
        jLabel_Sayac.setVisible(acilis);
        jLabel_KurtarmaKodu.setVisible(acilis);
        
       jTextField_KullaniciAdi.setVisible(!acilis);
       jPasswordField_KullaniciSifresi.setVisible(!acilis);
       jLabel_SifremiUnuttum.setVisible(!acilis);
        
       if(acilis ==false){
           jLabel_userLogin.setIcon(renkIkon.getUser());
           
          
           
       }else{
           
            jLabel_userLogin.setIcon(renkIkon.getUser2());
            
           
         }
       
    }
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_AnaPanel = new javax.swing.JPanel();
        jPanel_GirisIkon = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_GirisParametreleri = new javax.swing.JPanel();
        jPanel_Navigasyon = new javax.swing.JPanel();
        jLabel_cancel = new javax.swing.JLabel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_move = new javax.swing.JLabel();
        jPanel_KullaniciIkon = new javax.swing.JPanel();
        jLabel_userLogin = new javax.swing.JLabel();
        jLabel_KurtarmaKodu = new javax.swing.JLabel();
        jLabel_Sayac = new javax.swing.JLabel();
        jPanel_KullaniciBilgileri = new javax.swing.JPanel();
        jTextField_KullaniciAdi = new javax.swing.JTextField();
        jPasswordField_KullaniciSifresi = new javax.swing.JPasswordField();
        jTextField_KurtarmaKodu = new javax.swing.JTextField();
        jLabel_SifremiUnuttum = new javax.swing.JLabel();
        jButton_GirisYap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel_AnaPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/GirisEkrani.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_GirisIkonLayout = new javax.swing.GroupLayout(jPanel_GirisIkon);
        jPanel_GirisIkon.setLayout(jPanel_GirisIkonLayout);
        jPanel_GirisIkonLayout.setHorizontalGroup(
            jPanel_GirisIkonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_GirisIkonLayout.setVerticalGroup(
            jPanel_GirisIkonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_GirisParametreleri.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_Navigasyon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelBlack.png"))); // NOI18N
        jLabel_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_cancelMouseExited(evt);
            }
        });

        jLabel_minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizeBlack.png"))); // NOI18N
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseExited(evt);
            }
        });

        jLabel_move.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel_move.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/move.png"))); // NOI18N
        jLabel_move.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel_moveMouseDragged(evt);
            }
        });
        jLabel_move.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel_moveMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NavigasyonLayout = new javax.swing.GroupLayout(jPanel_Navigasyon);
        jPanel_Navigasyon.setLayout(jPanel_NavigasyonLayout);
        jPanel_NavigasyonLayout.setHorizontalGroup(
            jPanel_NavigasyonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NavigasyonLayout.createSequentialGroup()
                .addComponent(jLabel_move, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_minimize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_cancel)
                .addGap(19, 19, 19))
        );
        jPanel_NavigasyonLayout.setVerticalGroup(
            jPanel_NavigasyonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NavigasyonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_NavigasyonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel_cancel)
                    .addComponent(jLabel_minimize))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jLabel_move, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_KullaniciIkon.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_userLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_KullaniciIkonLayout = new javax.swing.GroupLayout(jPanel_KullaniciIkon);
        jPanel_KullaniciIkon.setLayout(jPanel_KullaniciIkonLayout);
        jPanel_KullaniciIkonLayout.setHorizontalGroup(
            jPanel_KullaniciIkonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_KullaniciIkonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_userLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        jPanel_KullaniciIkonLayout.setVerticalGroup(
            jPanel_KullaniciIkonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_KullaniciIkonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_userLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_KurtarmaKodu.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_KurtarmaKodu.setForeground(new java.awt.Color(102, 255, 255));
        jLabel_KurtarmaKodu.setText("Kurtarma kodunu giriniz");

        jLabel_Sayac.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel_Sayac.setForeground(new java.awt.Color(102, 255, 255));
        jLabel_Sayac.setText("120");

        jPanel_KullaniciBilgileri.setBackground(new java.awt.Color(255, 255, 255));

        jTextField_KullaniciAdi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_KullaniciAdi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kullanıcı Adı", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextField_KullaniciAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_KullaniciAdiKeyPressed(evt);
            }
        });

        jPasswordField_KullaniciSifresi.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jPasswordField_KullaniciSifresi.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kullanıcı Şifresi", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPasswordField_KullaniciSifresi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_KullaniciSifresiKeyPressed(evt);
            }
        });

        jTextField_KurtarmaKodu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTextField_KurtarmaKodu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Kurtarma Kodu", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jTextField_KurtarmaKodu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_KurtarmaKoduKeyPressed(evt);
            }
        });

        jLabel_SifremiUnuttum.setForeground(new java.awt.Color(51, 255, 255));
        jLabel_SifremiUnuttum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_SifremiUnuttum.setText("Şifremi unuttum");
        jLabel_SifremiUnuttum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_SifremiUnuttumMouseExited(evt);
            }
        });

        jButton_GirisYap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/enterBlue.png"))); // NOI18N
        jButton_GirisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GirisYapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_KullaniciBilgileriLayout = new javax.swing.GroupLayout(jPanel_KullaniciBilgileri);
        jPanel_KullaniciBilgileri.setLayout(jPanel_KullaniciBilgileriLayout);
        jPanel_KullaniciBilgileriLayout.setHorizontalGroup(
            jPanel_KullaniciBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_KullaniciBilgileriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_KullaniciBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton_GirisYap, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_SifremiUnuttum)
                    .addComponent(jTextField_KurtarmaKodu)
                    .addComponent(jPasswordField_KullaniciSifresi)
                    .addComponent(jTextField_KullaniciAdi))
                .addContainerGap())
        );
        jPanel_KullaniciBilgileriLayout.setVerticalGroup(
            jPanel_KullaniciBilgileriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_KullaniciBilgileriLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_KullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField_KullaniciSifresi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_KurtarmaKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_SifremiUnuttum)
                .addGap(18, 18, 18)
                .addComponent(jButton_GirisYap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_GirisParametreleriLayout = new javax.swing.GroupLayout(jPanel_GirisParametreleri);
        jPanel_GirisParametreleri.setLayout(jPanel_GirisParametreleriLayout);
        jPanel_GirisParametreleriLayout.setHorizontalGroup(
            jPanel_GirisParametreleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Navigasyon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_KullaniciIkon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_GirisParametreleriLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_KurtarmaKodu, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Sayac, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel_KullaniciBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_GirisParametreleriLayout.setVerticalGroup(
            jPanel_GirisParametreleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_GirisParametreleriLayout.createSequentialGroup()
                .addComponent(jPanel_Navigasyon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_KullaniciIkon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel_GirisParametreleriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_KurtarmaKodu)
                    .addComponent(jLabel_Sayac))
                .addGap(0, 0, 0)
                .addComponent(jPanel_KullaniciBilgileri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_AnaPanelLayout = new javax.swing.GroupLayout(jPanel_AnaPanel);
        jPanel_AnaPanel.setLayout(jPanel_AnaPanelLayout);
        jPanel_AnaPanelLayout.setHorizontalGroup(
            jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_AnaPanelLayout.createSequentialGroup()
                .addComponent(jPanel_GirisIkon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel_GirisParametreleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_AnaPanelLayout.setVerticalGroup(
            jPanel_AnaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_GirisIkon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_GirisParametreleri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseEntered
       
    
        
        jLabel_minimize.setIcon(renkIkon.getMinimize());
        
        
    }//GEN-LAST:event_jLabel_minimizeMouseEntered

    private void jLabel_minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseExited
       
          jLabel_minimize.setIcon(renkIkon.getMinimize2());
        
        
        
    }//GEN-LAST:event_jLabel_minimizeMouseExited

    private void jLabel_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelMouseExited
       
          jLabel_cancel.setIcon(renkIkon.getCancel2());
        
    }//GEN-LAST:event_jLabel_cancelMouseExited

    private void jLabel_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelMouseEntered
          jLabel_cancel.setIcon(renkIkon.getCancel());
    }//GEN-LAST:event_jLabel_cancelMouseEntered

    private void jLabel_cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_cancelMouseClicked
      
        System.exit(0); // Arayüz kapanır...
        
    }//GEN-LAST:event_jLabel_cancelMouseClicked

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
       
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_SifremiUnuttumMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseEntered
       
        jLabel_SifremiUnuttum.setForeground(Color.BLACK);
        
        
    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseEntered

    private void jLabel_SifremiUnuttumMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseExited
        
         jLabel_SifremiUnuttum.setForeground(renkIkon.getMavi());
         jLabel_SifremiUnuttum.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
         
    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseExited

    private void jLabel_SifremiUnuttumMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SifremiUnuttumMouseClicked
       
       
       
       String girilenKullaniciAdi = jTextField_KullaniciAdi.getText().toString();
       
       girilenKullaniciAdi = girilenKullaniciAdi.replaceAll(" ", "");
       
       jTextField_KullaniciAdi.setText(girilenKullaniciAdi);
       
       Kullanici kullanici ;
       
       boolean mailAdresiBulunduMu = false;
       
       
       if(!girilenKullaniciAdi.equals("")){ // Mail gönderilecek
           
           int dialogButton = JOptionPane.showConfirmDialog(this, "Kurtarma kodu e-posta adresinize gönderilsin mi?","Uyarı",JOptionPane.YES_NO_OPTION);

           
           if(dialogButton == 0){ // Evet ise
             
            
               
               try {
                   
                   
                    kullanici =  kullaniciIslemleri.kullaniciBul(girilenKullaniciAdi);
                    if(kullanici != null){
                       
                       initComponents2(true);
                       
                                         
                   mailAdresiBulunduMu = kullaniciIslemleri.sifremiUnuttum(kullanici);
                   
 
                 
                   if(mailAdresiBulunduMu){
                       
                       
                    
                   
                   // True veya False olma durumunu inceleyecez...
                   SwingWorker<Boolean,Integer> worker = new SwingWorker(){
                   @Override
                   protected Object doInBackground() throws Exception {
                     
                   
                            
                       for(int i = 120; i>=0 ; i--){
                           
                       if(!sifreSonuc){
                           
                           
                         jLabel_Sayac.setText(String.valueOf(i));
                         Thread.sleep(1000); // 1 sn 
                         
                         
                       }else{
                           
                          sayacDurdur = true;
                          
                          return true; // for döngüsünü bitirdik.
                           
                       }
               
                       }
                       
          
                     return true;  
                   }

                   @Override
                   protected void done() {
                       
                       initComponents2(false);
                       
                       if(!sayacDurdur){
                           
                          JOptionPane.showMessageDialog(GirisEkranı.this,"Süre bitti!");
                           
                       }else{
                           
                           JOptionPane.showMessageDialog(GirisEkranı.this,kullanici.getKullaniciSifre());
                           jPasswordField_KullaniciSifresi.setText(kullanici.getKullaniciSifre());
                           
                       }
                       
        
                   }
                   
                   
                   
               };
               
               worker.execute();
                    
                    
               }else{
                       
                     JOptionPane.showMessageDialog(this,"E-mail bulunamadı.");
                   }
                    }
                       
                       else{
                      
                       throw new NullPointerException();
                       
                   }
                             
                 
                   
                   
               } catch (SQLException ex) {
                   Logger.getLogger(GirisEkranı.class.getName()).log(Level.SEVERE, null, ex);
                   
                } catch (MessagingException ex){
                    
                      Logger.getLogger(GirisEkranı.class.getName()).log(Level.SEVERE, null, ex);
                      
                }
               
                catch(NullPointerException ex){
                    
                 JOptionPane.showMessageDialog(this,"Böyle bir kullanıcı adı yok!");
                 
                }
    
           }else{
               
               
           }
           
           
       }else{
           
           JOptionPane.showMessageDialog(this,"Kullanıcı adınızı girmediniz!");
           
       }
  
       
     /*  jTextField_KullaniciAdi.setVisible(false);
       jPasswordField_KullaniciSifresi.setVisible(false); */
        
    }//GEN-LAST:event_jLabel_SifremiUnuttumMouseClicked

    private void jLabel_moveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_moveMousePressed
        
      posX = evt.getX();
      posY = evt.getY();
      
        
    }//GEN-LAST:event_jLabel_moveMousePressed

    private void jLabel_moveMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_moveMouseDragged
        
       this.setLocation(evt.getXOnScreen()-posX-350,evt.getYOnScreen()-posY); 
        
    }//GEN-LAST:event_jLabel_moveMouseDragged

    private void jButton_GirisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GirisYapActionPerformed
    
       sifreKurtarmaIslemi = jTextField_KurtarmaKodu.isVisible();
               
       
       girisEkranIslemleri = new GirisEkranIslemleri(jTextField_KullaniciAdi,jPasswordField_KullaniciSifresi,jTextField_KurtarmaKodu);        
       
       String girilenKullaniciAdi = jTextField_KullaniciAdi.getText().toString();
       String girilenKullaniciSifre = new String(jPasswordField_KullaniciSifresi.getPassword());
       
       
       
       boolean girisSonuc = false;
       boolean sifreSonuc = false;
       
       
       Kullanici kullanici;
       
      if(sifreKurtarmaIslemi == false){
          
           try {
               
               girisSonuc = girisEkranIslemleri.bosGirisKontrol();
  
             if(girisSonuc){
                 
             kullanici = kullaniciIslemleri.kullaniciBul(girilenKullaniciAdi,girilenKullaniciSifre);
            
               if(kullanici != null){
                   
                   // JFRAME oluşacak...
            
                   this.setVisible(false);
                   
                   OBSUI obsui = new OBSUI(kullanici);
                   
                   obsui.setVisible(true);
          
                   
               }else {  // kullanici degişkeni null değere sahip ise
                   
                   throw new NullPointerException();
               }
                 
            }else{
            
           JOptionPane.showMessageDialog(this,girisEkranIslemleri.getSonucMesaj(),"Bilgilendirme", 1);
            
            }
        
    
               
           } catch (SQLException ex) {
               
               Logger.getLogger(GirisEkranı.class.getName()).log(Level.SEVERE, null, ex);
           }catch(NullPointerException ex){
               
               JOptionPane.showMessageDialog(this,"Kullanıcı bulunamadı!");
               
           }
      

       }else{
          
       
          sifreSonuc = girisEkranIslemleri.sifreKurtar(mailIslemleri.getSifreKurtarmaKodu());
          
          if(sifreSonuc){
              
              this.sifreSonuc = true;
              
          }else{
              
              JOptionPane.showMessageDialog(this,girisEkranIslemleri.getSonucMesaj(),"Bilgilendirme",1);
   
          }
         
      }
        
    }//GEN-LAST:event_jButton_GirisYapActionPerformed

    private void jTextField_KullaniciAdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KullaniciAdiKeyPressed
       
        if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            
             jButton_GirisYap.doClick();
            
        }
        
    }//GEN-LAST:event_jTextField_KullaniciAdiKeyPressed

    private void jPasswordField_KullaniciSifresiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_KullaniciSifresiKeyPressed
        
         if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            
             jButton_GirisYap.doClick();
            
        }
    }//GEN-LAST:event_jPasswordField_KullaniciSifresiKeyPressed

    private void jTextField_KurtarmaKoduKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_KurtarmaKoduKeyPressed
        
         if(evt.getKeyChar() == KeyEvent.VK_ENTER){
            
             jButton_GirisYap.doClick();
            
        }
        
    }//GEN-LAST:event_jTextField_KurtarmaKoduKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GirisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GirisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GirisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GirisEkranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GirisEkranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_GirisYap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_KurtarmaKodu;
    private javax.swing.JLabel jLabel_Sayac;
    private javax.swing.JLabel jLabel_SifremiUnuttum;
    private javax.swing.JLabel jLabel_cancel;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_move;
    private javax.swing.JLabel jLabel_userLogin;
    private javax.swing.JPanel jPanel_AnaPanel;
    private javax.swing.JPanel jPanel_GirisIkon;
    private javax.swing.JPanel jPanel_GirisParametreleri;
    private javax.swing.JPanel jPanel_KullaniciBilgileri;
    private javax.swing.JPanel jPanel_KullaniciIkon;
    private javax.swing.JPanel jPanel_Navigasyon;
    private javax.swing.JPasswordField jPasswordField_KullaniciSifresi;
    private javax.swing.JTextField jTextField_KullaniciAdi;
    private javax.swing.JTextField jTextField_KurtarmaKodu;
    // End of variables declaration//GEN-END:variables
}
